BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "WORKOUTS" (
	"id"	INTEGER,
	"day"	INTEGER,
	"minth"	INTEGER,
	"year"	INTEGER,
	"type"	INTEGER,
	"duration"	INTEGER,
	"calories"	REAL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "CONFIG" (
	"type"	INTEGER,
	"coefficient_duration"	REAL,
	"coefficient_height"	REAL,
	"coefficient_weight"	REAL,
	PRIMARY KEY("type")
);
CREATE TABLE IF NOT EXISTS "USER" (
	"id"	INTEGER,
	"name"	TEXTge,
	"height"	REAL,
	"weight"	REAL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "GOALS" (
	"id"	INTEGER,
	"goal"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);
INSERT INTO "CONFIG" VALUES (0,NULL,NULL,NULL);
INSERT INTO "CONFIG" VALUES (1,0.4,1.0,0.8);
INSERT INTO "CONFIG" VALUES (2,0.5,1.0,0.6);
INSERT INTO "CONFIG" VALUES (3,0.4,0.9,0.4);
INSERT INTO "CONFIG" VALUES (4,0.4,1.0,0.8);
INSERT INTO "CONFIG" VALUES (5,0.3,1.1,1.2);
INSERT INTO "CONFIG" VALUES (6,0.8,1.0,1.4);
INSERT INTO "CONFIG" VALUES (7,0.2,1.2,1.4);
INSERT INTO "CONFIG" VALUES (8,0.3,1.1,1.5);
INSERT INTO "CONFIG" VALUES (9,0.4,1.1,1.4);
INSERT INTO "CONFIG" VALUES (10,0.4,2.0,2.4);
INSERT INTO "CONFIG" VALUES (11,0.6,1.8,3.4);
INSERT INTO "CONFIG" VALUES (12,1.1,1.9,3.2);
INSERT INTO "CONFIG" VALUES (13,1.0,1.7,1.0);
INSERT INTO "CONFIG" VALUES (14,0.3,1.4,0.3);
INSERT INTO "CONFIG" VALUES (15,0.2,2.0,0.2);
COMMIT;
